{% set version = "4.0.1" %}

package:
  name: bear
  version: {{ version }}

source:
  url: https://github.com/rizsotto/Bear/archive/refs/tags/{{ version }}.tar.gz
  sha256: 64bcd65a333c6060d929c62b461edbd172a7256e42aae6d327982a0ce643a20c

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja
    - pkg-config
    - libgrpc  # [build_platform != target_platform]

  host:
    - libgrpc
    - zlib
    - spdlog
    - nlohmann_json

  run:
    - libprotobuf

test:
  commands:
    - test -f ${PREFIX}/bin/bear
    - bear -- test -d .

about:
  home: https://github.com/rizsotto/Bear
  license: GPL-3.0-only
  license_file: COPYING
  summary: Bear is a tool that generates a compilation database for clang tooling.
  description:
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - mwittgen
    - h-vetinari
    - lindsayad
