{% set version = "3.1.4" %}

package:
  name: bear
  version: {{ version }}

source:
  url: https://github.com/rizsotto/Bear/archive/refs/tags/{{ version }}.tar.gz
  sha256: a1105023795b3e1b9abc29c088cdec5464cc9f3b640b5078dc90a505498da5ff

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
    - libgrpc

  host:
    - libgrpc
    - spdlog
    - nlohmann_json

  run:
    - libprotobuf

test:
  commands:
    - test -f ${PREFIX}/bin/bear
    - bear -- test -d .

about:
  home: https://github.com/rizsotto/Bear
  license: GPL-3.0-only
  license_file: COPYING
  summary: Bear is a tool that generates a compilation database for clang tooling.
  description:
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - mwittgen
    - h-vetinari
