{% set version = "3.1.3" %}

package:
  name: bear
  version: {{ version }}

source:
  url: https://github.com/rizsotto/Bear/archive/refs/tags/{{ version }}.tar.gz
  sha256: 8314438428069ffeca15e2644eaa51284f884b7a1b2ddfdafe12152581b13398  

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
    - protobuf

  host:
    - libgrpc
    - spdlog
    - nlohmann_json
    - fmt
    - libprotobuf
  run:
    - libgrpc
    - spdlog
    - nlohmann_json
    - fmt
    - libprotobuf

test:
  commands:
    - test -f ${PREFIX}/bin/bear
    - bear -- test -d .

about:
  home: https://github.com/rizsotto/Bear
  license: GPL-3.0-only
  license_file: COPYING
  summary: Bear is a tool that generates a compilation database for clang tooling.
  description:
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - mwittgen
    - h-vetinari
