{% set version = "3.1.0" %}

package:
  name: bear
  version: {{ version }}

source:
  url: https://github.com/rizsotto/Bear/archive/refs/tags/{{ version }}.tar.gz
  sha256: 33c1f4663d94508f11cbd999dd5571359be7d15b0f473f7cfbea2c0b3190a891

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja
    - pkg-config
    - libgrpc

  host:
    - libgrpc =1.51.1
    - spdlog
    - nlohmann_json
    - libabseil ==20220623.*

  run:
    - libprotobuf
    - libgrpc =1.51.1
    - libabseil ==20220623.*

test:
  commands:
    - test -f ${PREFIX}/bin/bear
    - bear -- test -d .

about:
  home: https://github.com/rizsotto/Bear
  license: GPL-3.0-only
  license_file: COPYING
  summary: Bear is a tool that generates a compilation database for clang tooling.
  description:
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - mwittgen
    - h-vetinari
