{% set version = "3.0.20" %}

package:
  name: bear
  version: {{ version }}

source:
  url: https://github.com/rizsotto/Bear/archive/refs/tags/{{ version }}.tar.gz
  sha256: 45cfcdab07f824f6c06c9776701156f7a04b23eadd25ecbc88c188789a447cc7

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
    - libgrpc

  host:
    - libgrpc
    - spdlog
    - nlohmann_json

  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.12") }}  # [osx and x86_64]
    - libprotobuf

test:
  commands:
    - test -f ${PREFIX}/bin/bear
    - bear -- test -d .

about:
  home: https://github.com/rizsotto/Bear
  license: GPL-3.0-only
  license_file: COPYING
  summary: Bear is a tool that generates a compilation database for clang tooling.
  description:
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - mwittgen
    - h-vetinari
