{% set name = "bear" %}
{% set version = "3.0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rizsotto/Bear/archive/refs/tags/{{ version }}.tar.gz
  sha256: ae94047c79b4f48462b66981f66a67b6a833d75d4c40e7afead491b1865f1142

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - grpc-cpp  {{ grpc_cpp }}

  host:
    - grpc-cpp  {{ grpc_cpp }}
    - spdlog
    - nlohmann_json

  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.12") }}  # [osx and x86_64]
    - libprotobuf

test:
  commands:
    - test -f ${PREFIX}/bin/bear
    - bear -- test -d .

about:
  home: https://github.com/rizsotto/Bear
  license: GPL-3.0-only
  license_file: COPYING
  summary: Bear is a tool that generates a compilation database for clang tooling.
  description:
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - mwittgen
